### ISSUE TITLE
where is the following data, thanks.

### ISSUE THREAD

**Issue by liamxg** [noemielefrancq/GlobalPhylogeographyPertussis#2]
Estimate_relative_fitness/Output_WCV_booster_ref3_fit_all.rds

**Comment by noemielefrancq** [comment]
Hi, to get this data you need to run the model, the file is unfortunately too big for GitHub.

**Comment by liamxg** [comment]
thanks, I like your model, but do not know how to run the model.

**Comment by noemielefrancq** [comment]
Thank you, I will update the documentation soon to provide more details about how to run the model.

**Comment by liamxg** [comment]
Thanks, that's great.

**Comment by liamxg** [comment]
can i get your email, thanks.

**Comment by noemielefrancq** [comment]
Dear Liam, 
I have added in the fitness folder a documentation on the fitness model ' [BP_fitness_model_intro.md.html](https://github.com/noemielefrancq/GlobalPhylogeographyPertussis/blob/main/Fitness_model/BP_fitness_model_intro.md.html)'. I am still working on it but should you have any question, please feel free to contact me. My email address is at the top of the document.
I have also added a file 'toy_chain.rds', so that you can run the downstream analysis and plotting script. 
Best,
Noémie

**Comment by liamxg** [comment]
@noemielefrancq you are so nice, I am very appreciated for this, thanks.
